### PR TITLE
INCOMPLETE: Added profit field for overlay with profit calculation 

### PR DESCRIPTION
**Pull request by nofatigue**
I opened this pull request to check if you are interested in such features related to profit tracking,
that will calculate how much profit you've made, per hour, in total, including items you've just banked
for people going on money making.
I added a profit field for starters:
image

### CODE REVIEW

**Review by wikiworm — CHANGES_REQUESTED** [review]
Refactoring in InventoryValuePlugin LGTM and new code looks great! There is currently no contribution guidelines (which I will add soon) but please make member variables camel case instead of pascal case. (i.e. change StartingInventoryValue, CurrentInventoryValue, and CurrentProfit to, startingInventoryValue, currentInventoryValue, and currentProfit.)

**Comment by nofatigue** [comment]
Hey, I think I will continue develop in a different repo now, since my code is becoming a pretty different plugin with a different goal. I will sure to have credit to your repo which I've forked from.

**Comment by nofatigue** [comment]
Hi :) Is it ok if just add a credit and link in my README file?
( see https://github.com/nofatigue/runelite-plugin-ProfitTracker)

**Comment by wikiworm** [comment]
> Hi :) Is it ok if just add a credit and link in my README file?
> ( see https://github.com/nofatigue/runelite-plugin-ProfitTracker

Your plugin looks great -- glad I was able to inspire something!  I will go ahead and close this PR.

**Pull request closed without merging**
